name = "memos-lite-api"
main = "src/index.ts"
compatibility_date = "2023-12-01"

[env.production]
name = "memos-lite-api"

[env.development]
name = "memos-lite-api-dev"

[[d1_databases]]
binding = "DB"
database_name = "memos-lite"
database_id = "b583a081-c08d-4385-94c8-f3a214e91a6b"

[vars]
JWT_SECRET = "your-jwt-secret-key"
CORS_ORIGIN = "*" 